# this is production version of the project
version: '3'

services:
  web:
    build: .
    ports:
      - "4567:4567"
    volumes:
    - .:/usr/src/djparty
    - /usr/src/AccountGenerator/djparty
    command: ruby app.rb